### ISSUE TITLE
Gifted subs

### ISSUE THREAD

**Issue by TZilba** [JohnWolfson/Lakea-Stream-Assistant#145]
When subs are gifted, lakea calls the gifter and not the giftee a "fully fledged ranger":
![image](https://github.com/JohnWolfson/Lakea-Stream-Assistant/assets/112347659/f5472f88-19f1-4f7f-89ff-2b4e905cd315)

**Comment by JohnWolfson** [comment]
This is a notable observation that should be addressed, Lakea can detect the tier of sub but its currently unknown if she can detect if it is gifted or not. This should be investigated and the functionality implemented if it is missing, if not then the the configuration file for the deployed version should be updated.

**Comment by JohnWolfson** [comment]
After some investigation, Lakea can detect if a subscription is a gift or not. However, some tweaks are needed for Lakea to use this. Moving this issue into progress to be worked on.
