### ISSUE TITLE
test-command

### ISSUE THREAD

**Issue by TZilba** [JohnWolfson/Lakea-Stream-Assistant#66]
You need a: !YoLakeaUThere? command to test her.

**Comment by JohnWolfson** [comment]
This is a good idea to implement, some consideration should be given for if this command should be available for all users or moderators and above. Leaving issue in Triage until proper acceptance criteria has been determined, will then move into Todo.

**Comment by JohnWolfson** [comment]
Acceptance criteria has been determined, moving this issue in to Todo

Acceptance Criteria:

- Lakea has own inbuilt commands that can be ran
- Lakea has inbuilt status command that confirms shes still active
- Lakea logs status (LogLevel.Info)

**Comment by JohnWolfson** [comment]
This functionality has been implemented in the form of the !status command, about to merge the branch now
